### ISSUE TITLE
Ran it once, broke my entire Garry's Mod

### ISSUE THREAD

**Issue by 0xym0ron** [Lightoner/RunLuaMenu#1]
Injected this once to see what it could do, was unable to click the derma that it displayed or any other buttons in Garry's Mod.

Restarted the game to find that Garry's Mod was not accepting any input at all. 
Can't click buttons, open console, open Steam overlay, etc.
I've reinstalled, verified my game cache, and ran the factoryreset.bat.
Absolutely nothing is fixing this issue so I'd really love to know what this module is doing that could cause my entire game to be broken beyond repair.

pls fix thx

**Comment by 0xym0ron** [comment]
forgot to mention that restarting my PC fixed the issue.
Would still like to know what causes this

**Comment by Lightoner** [comment]
I will not update it, there are better alternative if you search to run lua, my goal with this project was to send net message at specific interval, maybe one day I will do it with the sdk to avoid lua.
